### ISSUE TITLE
Remote Access

### ISSUE THREAD

**Issue by brianjking** [brianjking/hass-config#10]

**Comment by KinnaT** [comment]
- [ ] Assign permanent IP route to HA in router config
- [ ] Assign port to route
- [ ] Allow port external TCP/IP communication
- [ ] Configure external address (or navigate to ip:port)
- [ ] Configure HA to have a password (but only if accessing through that address??)

**Comment by brianjking** [comment]
Several of these items are already setup, however, not working since I recreated the HA install and need to re-work LetsEncrypt back in and this time plan to do so with NGINX.

**Comment by brianjking** [comment]
Testing in #5
