### ISSUE TITLE
Persistent z-wave device name

### ISSUE THREAD

**Issue by brianjking** [brianjking/hass-config#18]
http://www.domoticz.com/wiki/PersistentUSBDevices

**Comment by brianjking** [comment]
@CCOSTAN -- I'm having trouble getting this working, I'm on a RaspberryPi 3 using the AiO. Any tips? Thanks!

**Comment by CCOSTAN** [comment]
I've added labels using the OZWP program on the pi.  then when HA discovers them, they have a friendly name already.  I think they have added this naming feature directly into HA as well.  Check the DEV service under ZWAVE.
![image](https://cloud.githubusercontent.com/assets/2160436/23907594/05487ee0-08a8-11e7-8bec-6faf02bfd6d4.png)

**Comment by brianjking** [comment]
@CCOSTAN I'm talking about setting a persistent name/path for Z-Wave. Right now whenever my Pi reboots or if I remove the Z-Wave stick to pair a new sensor I have to update my configuration.yaml.

https://github.com/brianjking/hass-config/blob/master/configuration.yaml#L229-L230

http://hintshop.ludvig.co.nz/show/persistent-names-usb-serial-devices/

**Comment by CCOSTAN** [comment]
Aah.  Yeah.. that's what I did.

https://github.com/CCOSTAN/Home-AssistantConfig/blob/master/configuration.yaml#L102

**Comment by brianjking** [comment]
@CCOSTAN Yeah, I'm having trouble getting the correct information in order to set this. 👎

**Comment by CCOSTAN** [comment]
https://gitter.im/home-assistant/home-assistant?at=5718e207a3833fbc566a29c8

**Comment by CCOSTAN** [comment]
My File looks SLIGHTLY different.



`SUBSYSTEM=="tty", ATTRS{idVendor}=="0658", ATTRS{idProduct}=="0200", SYMLINK+="zwave"`

**Comment by brianjking** [comment]
How did you determine to put what you have versus what the person suggested in Gitter?

````
ACTION=="add", ATTRS{idVendor}=="0658", ATTRS{idProduct}=="0200" SYMLINK+="zwave"
````

**Comment by brianjking** [comment]
sudo nano /etc/udev/rules.d/99-usb-serial.rules

ACTION=="add", ATTRS{idVendor}=="0658", ATTRS{idProduct}=="0200" SYMLINK+="zwave"
